version: '3.5'
services:
  vue-app:
    stdin_open: true
    tty: true
    build:
      context: ./app
      target: build-vue
    command: yarn run serve
    volumes:
      - ./app:/app
    ports:
      - 39000:8080
    depends_on:
      - go-app

  go-app:
    build:
      context: ./server
      target: build-go
    command: realize start --run
    volumes:
      - ./server:/go/server
    ports:
      - 38080:8080

  # check production image
  # vue-check:
  #   build:
  #     context: .
  #     target: production-vue
  #     dockerfile: app/Dockerfile
  #   ports:
  #     - 49000:80
  #   depends_on:
  #     - go-check

  # go-check:
  #   build:
  #     context: .
  #     target: production-go
  #     dockerfile: server/Dockerfile
  #   ports:
  #     - 48080:8080
